 const FETCH_WEATHER_PENDING = 'FETCH_WEATHER_PENDING';
 const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS';
 const FETCH_WEATHER_ERROR = 'FETCH_WEATHER_ERROR';
 const FETCH_LOCATION_SUCCESS = 'FETCH_LOCATION_SUCCESS';

 export {
    FETCH_WEATHER_PENDING,
    FETCH_WEATHER_SUCCESS,
    FETCH_WEATHER_ERROR,
    FETCH_LOCATION_SUCCESS
 }